// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/logic/logic.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_server_2flogic_2flogic_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_server_2flogic_2flogic_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include "server/common/messages.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_server_2flogic_2flogic_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_server_2flogic_2flogic_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_2flogic_2flogic_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace oceanim {

// ===================================================================


// ===================================================================

class LogicService_Stub;

class LogicService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline LogicService() {};
 public:
  virtual ~LogicService();

  typedef LogicService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::Ping* request,
                       ::oceanim::Pong* response,
                       ::google::protobuf::Closure* done);
  virtual void SendMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::NewMsg* request,
                       ::oceanim::MsgReply* response,
                       ::google::protobuf::Closure* done);
  virtual void PullData(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::Ping* request,
                       ::oceanim::Msgs* response,
                       ::google::protobuf::Closure* done);
  virtual void GetMsgs(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::MsgIdRange* request,
                       ::oceanim::Msgs* response,
                       ::google::protobuf::Closure* done);
  virtual void GetFriends(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::UserId* request,
                       ::oceanim::UserInfos* response,
                       ::google::protobuf::Closure* done);
  virtual void GetGroups(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::UserId* request,
                       ::oceanim::GroupInfos* response,
                       ::google::protobuf::Closure* done);
  virtual void GetGroupMembers(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::GroupId* request,
                       ::oceanim::UserInfos* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(LogicService);
};

class LogicService_Stub : public LogicService {
 public:
  LogicService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  LogicService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~LogicService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements LogicService ------------------------------------------

  void Test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::Ping* request,
                       ::oceanim::Pong* response,
                       ::google::protobuf::Closure* done);
  void SendMsg(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::NewMsg* request,
                       ::oceanim::MsgReply* response,
                       ::google::protobuf::Closure* done);
  void PullData(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::Ping* request,
                       ::oceanim::Msgs* response,
                       ::google::protobuf::Closure* done);
  void GetMsgs(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::MsgIdRange* request,
                       ::oceanim::Msgs* response,
                       ::google::protobuf::Closure* done);
  void GetFriends(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::UserId* request,
                       ::oceanim::UserInfos* response,
                       ::google::protobuf::Closure* done);
  void GetGroups(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::UserId* request,
                       ::oceanim::GroupInfos* response,
                       ::google::protobuf::Closure* done);
  void GetGroupMembers(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oceanim::GroupId* request,
                       ::oceanim::UserInfos* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(LogicService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace oceanim

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_server_2flogic_2flogic_2eproto
